//this file contains all song name
var list=[
    'Alan Walker - Faded(MP3_320K).mp3',
    'Ariana Grande ft. Nicki Minaj - Side To Side (Official Video) ft. Nicki Minaj(MP3_320K).mp3',
    'Atrangi Re_ Chaka Chak __A. R. Rahman_ Akshay K_ Sara A K_ Dhanush_ Shreya_Irshad_Aanand_ Bhushan K(MP3_320K).mp3',
    'B Praak _ Sach Keh Raha Hai _ Recreation _ Official Music Video _ RHTDM(MP3_320K).mp3',
    'Baarish Ki Jaaye _ B Praak Ft Nawazuddin Siddiqui _ Sunanda Sharma _ Jaani _ Arvindr Khaira _ DM(MP3_160K).mp3',
    'BAD MUNDA _ Jass Manak Ft. Emiway Bantai (Full Video) Satti Dhillon _ Deep Jandu _ GK _ Geet(MP3_320K).mp3',
    'Badshah - Jugnu (Official Video) _ Nikhita Gandhi _ Akanksha Sharma(MP3_320K).mp3',
    'BLACKPINK - _How You Like That_ DANCE PERFORMANCE VIDEO(MP3_320K).mp3',
    'BLACKPINK - _Ice Cream (with Selena Gomez)_ M_V(MP3_320K).mp3',
    'BLACKPINK - _Kill This Love_ M_V(MP3_320K).mp3',
    'BOL KAFFARA KYA HOGA LYRICAL - DJ Chetas _ Neha Kakkar _ Nusrat FatehAli Khan_Farhan_Lijo _ Anshul G(MP3_320K).mp3',
    'BROWN MUNDE - AP DHILLON _ GURINDER GILL _ SHINDA KAHLON _ GMINXR(MP3_128K).mp3',
    'Chand_Taro_Me_Nazar_Aaye_Chahera_Tera_(Love_Dholki_Mix)_Dj_Adarsh_Sk- Djshivaclub.com.mp3',
    'Dil Lauta Do Song _ Jubin Nautiyal_ Payal Dev _ Sunny K_ Saiyami K _ Kunaal V _ Navjit B _ Bhushan K(MP3_320K).mp3',
    'DJ Snake ft. Justin Bieber - Let Me Love You [Lyric Video](MP3_320K).mp3',
    'Harrdy Sandhu - Bijlee Bijlee ft Palak Tiwari _ Jaani _ BPraak _ Arvindr Khaira _ Desi Melodies(MP3_320K).mp3',
    'KANTA LAGA - Tony Kakkar_ Yo Yo Honey Singh_ Neha Kakkar _ Anshul Garg _ Latest Hindi Song 2021(MP3_320K).mp3',
    'Lut Gaye (Full Song) Emraan Hashmi_ Yukti _ Jubin N_ Tanishk B_ Manoj M _ Bhushan K _ Radhika-Vinay(MP3_128K).mp3',
    'Lyrical_ Khairiyat _ Chhichhore _ Nitesh Tiwari _ Arijit Singh _ Sushant_ Shraddha _ Pritam(MP3_160K).mp3',
    'Maroon 5 - Girls Like You ft. Cardi B (Official Music Video)(MP3_320K).mp3',
    'Master - Vaathi Coming Lyric _ Thalapathy Vijay _ Anirudh Ravichander _ Lokesh Kanagaraj(MP3_160K).mp3',
    'Nadiyon Paar (Let the Music Play) – Roohi _ Janhvi _ Sachin-Jigar _ Rashmeet_ Shamur_ IP Singh(MP3_160K).mp3',
    'Oo Antava..Oo Oo Antava (Telugu)Lyrical _Pushpa Songs _Allu Arjun_Rashmika _DSP _Sukumar _ Samantha(MP3_320K).mp3',
    'Pagla Pagli 2 Rap Song - ZB (Official music video) Pagla Pagli Song - Kolkata Rap Song  Kolkata song(MP3_320K).mp3',
    'Param Sundari -Official Video _ Mimi _ Kriti Sanon_ Pankaj Tripathi _ _A. R. Rahman_ Shreya _Amitabh(MP3_320K).mp3',
    'Ritviz - Liggi [Official Music Video](MP3_320K).mp3',
    'Saiyaan Ji ► Yo Yo Honey Singh_ Neha Kakkar_Nushrratt Bharuccha_  Lil G_ Hommie D_ Mihir G_Bhushan K(MP3_128K).mp3',
    'Sharaabi (Official Video) _ Simar Doraha _ MixSingh _ Latest Punjabi Songs 2020 _ Speed Records(MP3_320K).mp3',
    'Taro Ke Sahar Me_192(PaglaSongs) (1).mp3',
    'The Chainsmokers - Don_t Let Me Down (Official Video) ft. Daya(MP3_320K).mp3',
    '_Srivalli (Telugu) _ Pushpa - The Rise _ Allu Arjun_ Rashmika _ DSP _ Sid Sriram _ Sukumar(MP3_320K).mp3'
];